/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    carts: Cart;
    orders: Order;
    consents: Consent;
    feedbacks: Feedback;
    banners: Banner;
    'pickup-points': PickupPoint;
    'transport-companies': TransportCompany;
    discounts: Discount;
    companies: Company;
    'knowledge-topics': KnowledgeTopic;
    wishlists: Wishlist;
    notifications: Notification;
    'content-blocks': ContentBlock;
    'faq-topics': FaqTopic;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'pickup-points': PickupPointsSelect<false> | PickupPointsSelect<true>;
    'transport-companies': TransportCompaniesSelect<false> | TransportCompaniesSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'knowledge-topics': KnowledgeTopicsSelect<false> | KnowledgeTopicsSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'content-blocks': ContentBlocksSelect<false> | ContentBlocksSelect<true>;
    'faq-topics': FaqTopicsSelect<false> | FaqTopicsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'user' | 'admin' | 'superadmin';
  status: 'active' | 'blocked' | 'suspended';
  blockedUntil?: string | null;
  acceptedTerms: boolean;
  acceptedTermsVersion?: string | null;
  acceptedTermsAt?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  isPublic?: boolean | null;
  type?: ('certificate' | 'instruction' | 'license' | 'passport' | 'product' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  subtitle?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  isActive?: boolean | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  sku: string;
  title: string;
  description: string;
  category: number | Category;
  images?: (number | Media)[] | null;
  priceForIndividual: number;
  discount?: {
    isActive?: boolean | null;
    percentage?: number | null;
    amount?: number | null;
    validFrom?: string | null;
    validUntil?: string | null;
    minQuantity?: number | null;
  };
  status?: ('available' | 'preorder' | 'out_of_stock' | 'discontinued') | null;
  minOrderQuantity?: number | null;
  maxOrderQuantity?: number | null;
  isVisible?: boolean | null;
  showOnMainPage?: boolean | null;
  instructionType?: ('file' | 'link') | null;
  instructionFile?: (number | null) | Media;
  instructionLink?: string | null;
  specifications?:
    | {
        name: string;
        value: string;
        unit?: string | null;
        group?: string | null;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  upsellProducts?: (number | Product)[] | null;
  crossSellProducts?: (number | Product)[] | null;
  manufacturer?: string | null;
  warrantyMonths?: number | null;
  weight?: number | null;
  dimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  viewsCount?: number | null;
  purchasesCount?: number | null;
  finalPrice?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Корзины пользователей (одна корзина на пользователя)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user: number | User;
  items?:
    | {
        product: number | Product;
        /**
         * Минимум 1
         */
        quantity: number;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Генерируется автоматически
   */
  orderNumber: string;
  user: number | User;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  recipient: {
    fullName: string;
    phone: string;
    email: string;
    contactPerson?: string | null;
  };
  delivery: {
    method: 'door_to_door' | 'pickup_point' | 'transport_company';
    address?: {
      street?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    pickupPoint?: (number | null) | PickupPoint;
    transportCompany?: (number | null) | TransportCompany;
    trackingNumber?: string | null;
    estimatedDelivery?: string | null;
    notes?: string | null;
  };
  items?:
    | {
        product: number | Product;
        sku?: string | null;
        name?: string | null;
        quantity: number;
        unitPrice: number;
        discount?: number | null;
        totalPrice: number;
        weight?: number | null;
        dimensions?: {
          length?: number | null;
          width?: number | null;
          height?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  pricing: {
    subtotal: number;
    discount?: number | null;
    shippingCost?: number | null;
    tax?: number | null;
    total: number;
    currency?: string | null;
    productDiscounts?: number | null;
    centralDiscountAmount?: number | null;
    priceWithoutDiscount?: number | null;
    centralDiscountPercent?: number | null;
  };
  payment: {
    method: 'card' | 'cash' | 'invoice' | 'online';
    status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
    transactionId?: string | null;
    paidAt?: string | null;
    paymentDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  statusHistory?:
    | {
        status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
        changedAt?: string | null;
        changedBy: number | User;
        comment?: string | null;
        metadata?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  appliedDiscounts?:
    | {
        discountId?: (number | null) | Discount;
        name?: string | null;
        type?: ('quantity_based' | 'amount_based' | 'percentage_based') | null;
        discountPercent?: number | null;
        discountAmount?: number | null;
        condition?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        appliedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  cancellation?: {
    reason?: string | null;
    cancelledBy?: (number | null) | User;
    cancelledAt?: string | null;
    refundAmount?: number | null;
    notes?: string | null;
  };
  companyInfo?: {
    companyId?: (number | null) | Company;
    name?: string | null;
    address?: string | null;
    legalAddress?: string | null;
    taxNumber?: string | null;
    contactPerson?: string | null;
  };
  companyCreated?: boolean | null;
  companySelection?: {
    type?: ('existing' | 'new') | null;
    companyId?: string | null;
    taxNumber?: string | null;
  };
  attachments?: (number | Media)[] | null;
  notes?: string | null;
  internalNotes?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: ('web' | 'mobile' | 'api' | 'admin') | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-points".
 */
export interface PickupPoint {
  id: number;
  name: string;
  address: string;
  city?: string | null;
  phone?: string | null;
  workingHours?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-companies".
 */
export interface TransportCompany {
  id: number;
  name: string;
  phone?: string | null;
  website?: string | null;
  /**
   * Шаблон URL для отслеживания, например https://track.ru/{trackingNumber}
   */
  trackingUrlTemplate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  name: string;
  description?: string | null;
  type: 'percentage' | 'fixed' | 'quantity_based';
  discountPercent?: number | null;
  fixedAmount?: number | null;
  minTotalQuantity?: number | null;
  minTotalAmount?: number | null;
  appliesToAllProducts?: boolean | null;
  applicableCategories?: (number | Category)[] | null;
  applicableProducts?: (number | Product)[] | null;
  isActive?: boolean | null;
  isUnlimited?: boolean | null;
  startAt: string;
  endAt?: string | null;
  priority?: number | null;
  code?: string | null;
  totalUses?: number | null;
  totalDiscountAmount?: number | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  isCurrentlyActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  user: number | User;
  companyName: string;
  legalAddress: string;
  companyAddress?: string | null;
  taxNumber: string;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Согласия пользователей (политика конфиденциальности, оферта и т.д.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  title: string;
  /**
   * Только латиница, цифры, _ и -
   */
  slug: string;
  description?: string | null;
  content: string;
  /**
   * Внешняя ссылка на PDF/документ
   */
  documentUrl?: string | null;
  isRequired?: boolean | null;
  needsAcceptance: boolean;
  isActive: boolean;
  /**
   * Инкрементируется автоматически при изменении контента
   */
  version?: string | null;
  checksum?: string | null;
  lastUpdatedAt?: string | null;
  lastUpdatedBy?: (number | null) | User;
  /**
   * Заполняется автоматически при каждом изменении
   */
  history?:
    | {
        version: string;
        content: string;
        documentUrl?: string | null;
        changeDescription?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Заполните перед сохранением — попадёт в историю версий и будет очищено
   */
  _changeDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Обратная связь, баги и предложения от пользователей
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  title: string;
  description: string;
  type: 'bug' | 'improvement' | 'feature' | 'other';
  status?: ('new' | 'in_progress' | 'resolved' | 'closed' | 'duplicate' | 'wont_fix') | null;
  priority?: ('low' | 'medium' | 'high' | 'critical') | null;
  user?: (number | null) | User;
  userEmail?: string | null;
  userName?: string | null;
  userRole?: ('user' | 'lawyer' | 'admin' | 'moderator') | null;
  assignedTo?: (number | null) | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  attachments?: (number | Media)[] | null;
  /**
   * Видны только сотрудникам
   */
  internalNotes?:
    | {
        note: string;
        createdBy?: (number | null) | User;
        createdAt?: string | null;
        isPrivate?: boolean | null;
        id?: string | null;
      }[]
    | null;
  viewCount?: number | null;
  upvotes?: number | null;
  upvotedBy?: (number | User)[] | null;
  relatedTo?: (number | Feedback)[] | null;
  duplicateOf?: (number | null) | Feedback;
  resolvedAt?: string | null;
  closedAt?: string | null;
  dueDate?: string | null;
  deviceInfo?: {
    userAgent?: string | null;
    platform?: string | null;
    os?: string | null;
    browser?: string | null;
    screenResolution?: string | null;
  };
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Промо-баннеры и системные уведомления
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  media?: (number | Media)[] | null;
  action?: ('none' | 'link' | 'modal' | 'redirect') | null;
  /**
   * URL для Link/Redirect, ID модалки для Modal
   */
  actionPayload?: string | null;
  startAt?: string | null;
  /**
   * Оставьте пустым для бессрочного показа
   */
  endAt?: string | null;
  repeatable?: boolean | null;
  priority?: number | null;
  status?: ('draft' | 'active' | 'scheduled' | 'archived') | null;
  isSystem?: boolean | null;
  targeting?: {
    /**
     * Оставьте пустым — баннер виден всем
     */
    roles?: ('user' | 'lawyer' | 'admin' | 'moderator')[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-topics".
 */
export interface KnowledgeTopic {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  position?: number | null;
  featured?: boolean | null;
  published?: boolean | null;
  publishedAt?: string | null;
  author?: (number | null) | User;
  content?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            label: string;
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'link';
          }
      )[]
    | null;
  readingTime?: number | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  user: number | User;
  items?:
    | {
        product: number | Product;
        addedAt?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  totalItems?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type?:
    | (
        | 'system'
        | 'subscription_match'
        | 'chat'
        | 'review'
        | 'order'
        | 'promotion'
        | 'discount'
        | 'product'
        | 'login_from_new_device'
      )
    | null;
  title: string;
  body: string;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  link?: string | null;
  isRead?: boolean | null;
  readAt?: string | null;
  pushStatus?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks".
 */
export interface ContentBlock {
  id: number;
  title: string;
  subtitle: string;
  image?: (number | null) | Media;
  button?: {
    text?: string | null;
    action?: string | null;
    style?: ('primary' | 'secondary' | 'outline') | null;
  };
  description?: string | null;
  position?: number | null;
  isActive?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-topics".
 */
export interface FaqTopic {
  id: number;
  title: string;
  description?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  questions?:
    | {
        question: string;
        answer: string;
        order?: number | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'pickup-points';
        value: number | PickupPoint;
      } | null)
    | ({
        relationTo: 'transport-companies';
        value: number | TransportCompany;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'knowledge-topics';
        value: number | KnowledgeTopic;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'content-blocks';
        value: number | ContentBlock;
      } | null)
    | ({
        relationTo: 'faq-topics';
        value: number | FaqTopic;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  blockedUntil?: T;
  acceptedTerms?: T;
  acceptedTermsVersion?: T;
  acceptedTermsAt?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  order?: T;
  isActive?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  sku?: T;
  title?: T;
  description?: T;
  category?: T;
  images?: T;
  priceForIndividual?: T;
  discount?:
    | T
    | {
        isActive?: T;
        percentage?: T;
        amount?: T;
        validFrom?: T;
        validUntil?: T;
        minQuantity?: T;
      };
  status?: T;
  minOrderQuantity?: T;
  maxOrderQuantity?: T;
  isVisible?: T;
  showOnMainPage?: T;
  instructionType?: T;
  instructionFile?: T;
  instructionLink?: T;
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        unit?: T;
        group?: T;
        isVisible?: T;
        id?: T;
      };
  relatedProducts?: T;
  upsellProducts?: T;
  crossSellProducts?: T;
  manufacturer?: T;
  warrantyMonths?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  viewsCount?: T;
  purchasesCount?: T;
  finalPrice?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        addedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  status?: T;
  recipient?:
    | T
    | {
        fullName?: T;
        phone?: T;
        email?: T;
        contactPerson?: T;
      };
  delivery?:
    | T
    | {
        method?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        pickupPoint?: T;
        transportCompany?: T;
        trackingNumber?: T;
        estimatedDelivery?: T;
        notes?: T;
      };
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        name?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        totalPrice?: T;
        weight?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        id?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        shippingCost?: T;
        tax?: T;
        total?: T;
        currency?: T;
        productDiscounts?: T;
        centralDiscountAmount?: T;
        priceWithoutDiscount?: T;
        centralDiscountPercent?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        transactionId?: T;
        paidAt?: T;
        paymentDetails?: T;
      };
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        comment?: T;
        metadata?: T;
        id?: T;
      };
  appliedDiscounts?:
    | T
    | {
        discountId?: T;
        name?: T;
        type?: T;
        discountPercent?: T;
        discountAmount?: T;
        condition?: T;
        appliedAt?: T;
        id?: T;
      };
  cancellation?:
    | T
    | {
        reason?: T;
        cancelledBy?: T;
        cancelledAt?: T;
        refundAmount?: T;
        notes?: T;
      };
  companyInfo?:
    | T
    | {
        companyId?: T;
        name?: T;
        address?: T;
        legalAddress?: T;
        taxNumber?: T;
        contactPerson?: T;
      };
  companyCreated?: T;
  companySelection?:
    | T
    | {
        type?: T;
        companyId?: T;
        taxNumber?: T;
      };
  attachments?: T;
  notes?: T;
  internalNotes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  source?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  documentUrl?: T;
  isRequired?: T;
  needsAcceptance?: T;
  isActive?: T;
  version?: T;
  checksum?: T;
  lastUpdatedAt?: T;
  lastUpdatedBy?: T;
  history?:
    | T
    | {
        version?: T;
        content?: T;
        documentUrl?: T;
        changeDescription?: T;
        createdAt?: T;
        id?: T;
      };
  _changeDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  status?: T;
  priority?: T;
  user?: T;
  userEmail?: T;
  userName?: T;
  userRole?: T;
  assignedTo?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  attachments?: T;
  internalNotes?:
    | T
    | {
        note?: T;
        createdBy?: T;
        createdAt?: T;
        isPrivate?: T;
        id?: T;
      };
  viewCount?: T;
  upvotes?: T;
  upvotedBy?: T;
  relatedTo?: T;
  duplicateOf?: T;
  resolvedAt?: T;
  closedAt?: T;
  dueDate?: T;
  deviceInfo?:
    | T
    | {
        userAgent?: T;
        platform?: T;
        os?: T;
        browser?: T;
        screenResolution?: T;
      };
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  media?: T;
  action?: T;
  actionPayload?: T;
  startAt?: T;
  endAt?: T;
  repeatable?: T;
  priority?: T;
  status?: T;
  isSystem?: T;
  targeting?:
    | T
    | {
        roles?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-points_select".
 */
export interface PickupPointsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  phone?: T;
  workingHours?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-companies_select".
 */
export interface TransportCompaniesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  website?: T;
  trackingUrlTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  discountPercent?: T;
  fixedAmount?: T;
  minTotalQuantity?: T;
  minTotalAmount?: T;
  appliesToAllProducts?: T;
  applicableCategories?: T;
  applicableProducts?: T;
  isActive?: T;
  isUnlimited?: T;
  startAt?: T;
  endAt?: T;
  priority?: T;
  code?: T;
  totalUses?: T;
  totalDiscountAmount?: T;
  createdBy?: T;
  updatedBy?: T;
  isCurrentlyActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  user?: T;
  companyName?: T;
  legalAddress?: T;
  companyAddress?: T;
  taxNumber?: T;
  contactPerson?: T;
  phone?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-topics_select".
 */
export interface KnowledgeTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  position?: T;
  featured?: T;
  published?: T;
  publishedAt?: T;
  author?: T;
  content?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  readingTime?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        addedAt?: T;
        notes?: T;
        id?: T;
      };
  totalItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  body?: T;
  data?: T;
  link?: T;
  isRead?: T;
  readAt?: T;
  pushStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-blocks_select".
 */
export interface ContentBlocksSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  button?:
    | T
    | {
        text?: T;
        action?: T;
        style?: T;
      };
  description?: T;
  position?: T;
  isActive?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metadata?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-topics_select".
 */
export interface FaqTopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  isActive?: T;
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        order?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  companyName: string;
  logo: number | Media;
  legalAddress?: string | null;
  physicalAddress?: string | null;
  phones?:
    | {
        type?: ('support' | 'sales' | 'general' | 'fax' | 'accounting' | 'other') | null;
        value: string;
        description?: string | null;
        isPrimary?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        type?: ('general' | 'support' | 'info' | 'sales' | 'security' | 'hr' | 'other') | null;
        value: string;
        description?: string | null;
        isPrimary?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'telegram' | 'whatsapp' | 'vk' | 'github' | 'max' | 'other';
        url: string;
        title?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  otherContacts?:
    | {
        type: 'messenger' | 'forum' | 'custom' | 'chat' | 'bot';
        name: string;
        value: string;
        description?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  restrictions?: {
    disableRegistration?: boolean | null;
    disableOrdering?: boolean | null;
  };
  workingHours?: string | null;
  map?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: знаки, светофоры, дорожные ограждения
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  legalAddress?: T;
  physicalAddress?: T;
  phones?:
    | T
    | {
        type?: T;
        value?: T;
        description?: T;
        isPrimary?: T;
        sortOrder?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        type?: T;
        value?: T;
        description?: T;
        isPrimary?: T;
        sortOrder?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        title?: T;
        sortOrder?: T;
        id?: T;
      };
  otherContacts?:
    | T
    | {
        type?: T;
        name?: T;
        value?: T;
        description?: T;
        sortOrder?: T;
        id?: T;
      };
  restrictions?:
    | T
    | {
        disableRegistration?: T;
        disableOrdering?: T;
      };
  workingHours?: T;
  map?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}